# Generated by Django 5.0 on 2023-12-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nevin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Relevent_skill', models.TextField(max_length=400)),
                ('professional_Development', models.CharField(max_length=200)),
                ('works', models.TextField(max_length=800)),
                ('image', models.ImageField(upload_to='user_images')),
            ],
        ),
    ]
