# Generated by Django 5.0 on 2023-12-22 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nevin',
            old_name='professional_Development',
            new_name='Professional_Development',
        ),
    ]
