# Generated by Django 5.0 on 2023-12-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0002_rename_professional_development_nevin_professional_development'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nevin',
            name='image',
            field=models.ImageField(upload_to='nevin'),
        ),
    ]
