# Generated by Django 5.0 on 2023-12-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_alter_nevin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nevin',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
