# Generated by Django 5.0 on 2023-12-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0004_alter_nevin_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nevin',
            name='image',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
