# Generated by Django 4.2.7 on 2023-12-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0005_alter_nevin_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='one',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
